name: Deploy Frontend

on:
  push:
    branches:
    - master
    paths:
    - "frontend/**"

jobs:
  Build, Test, deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, test and deploy
      run: |
        cd frontend
        yarn test
        yarn build
        yarn deploy
      env:
        CI: true
        NODE_ENV: production
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
