name: Deploy The Full Stack

on:
  push:
    branches:
    - master
    paths:
    - "backend/**"
    - "frontend/**"
    - "fullstack/**"
    - ".github/workflows/deploy-the-full-stack.yml"

jobs:
  Build-Deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build, deploy backend
      run: |
        cd backend
        yarn install --production
        yarn build
        yarn deploy
        yarn copy-data-2-fe
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: yarn install frontend functions
      run: |
        cd frontend/functions
        yarn install --ignore-engines
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name: yarn install, build, deploy frontend
      run: |
        cd frontend
        yarn install --production
        yarn build
        yarn deploy
      env:
        CI: true
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
